"""Change courier model, added branch from 

Revision ID: 8efcc658e497
Revises: 32563377ff9f
Create Date: 2025-02-24 13:42:23.320948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8efcc658e497'
down_revision: Union[str, None] = '32563377ff9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('couriers', sa.Column('branch_from', sa.Integer(), nullable=False))
    op.drop_column('couriers', 'locate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('couriers', sa.Column('locate', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('couriers', 'branch_from')
    # ### end Alembic commands ###
